<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Webdriver" duration-ms="39704" started-at="2020-04-12T15:54:30Z" finished-at="2020-04-12T15:55:10Z">
    <groups>
    </groups>
    <test name="test" duration-ms="39704" started-at="2020-04-12T15:54:30Z" finished-at="2020-04-12T15:55:10Z">
      <class name="Testng.NewTest1">
        <test-method status="PASS" signature="launch()[pri:0, instance:Testng.NewTest1@3f0ee7cb]" name="launch" is-config="true" duration-ms="15972" started-at="2020-04-12T15:54:30Z" finished-at="2020-04-12T15:54:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="verifytitle()[pri:0, instance:Testng.NewTest1@3f0ee7cb]" name="verifytitle" duration-ms="33" started-at="2020-04-12T15:54:46Z" finished-at="2020-04-12T15:54:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifytitle -->
        <test-method status="PASS" signature="close()[pri:0, instance:Testng.NewTest1@3f0ee7cb]" name="close" is-config="true" duration-ms="2843" started-at="2020-04-12T15:54:46Z" finished-at="2020-04-12T15:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="launch()[pri:0, instance:Testng.NewTest1@3f0ee7cb]" name="launch" is-config="true" duration-ms="12757" started-at="2020-04-12T15:54:49Z" finished-at="2020-04-12T15:55:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="FAIL" signature="verifyurl()[pri:0, instance:Testng.NewTest1@3f0ee7cb]" name="verifyurl" duration-ms="13" started-at="2020-04-12T15:55:02Z" finished-at="2020-04-12T15:55:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [edureka.com] but found [https://www.edureka.co/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [edureka.com] but found [https://www.edureka.co/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Testng.NewTest1.verifyurl(NewTest1.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyurl -->
        <test-method status="PASS" signature="close()[pri:0, instance:Testng.NewTest1@3f0ee7cb]" name="close" is-config="true" duration-ms="2142" started-at="2020-04-12T15:55:02Z" finished-at="2020-04-12T15:55:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Testng.NewTest1 -->
      <class name="Testng.NewTest2">
        <test-method status="PASS" signature="verifytitle1()[pri:0, instance:Testng.NewTest2@75bd9247]" name="verifytitle1" duration-ms="5900" started-at="2020-04-12T15:55:04Z" finished-at="2020-04-12T15:55:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifytitle1 -->
      </class> <!-- Testng.NewTest2 -->
    </test> <!-- test -->
  </suite> <!-- Webdriver -->
</testng-results>
